"use client";

import { useState } from "react";
import { Check, Pencil, Plus, Tag, Trash2, X } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { fakeGenres } from "@/lib/fake-data";

interface Genre { id: string; name: string }

export default function GenresPage() {
  const [genres, setGenres] = useState<Genre[]>(fakeGenres);
  const [newGenre, setNewGenre] = useState("");
  const [editing, setEditing] = useState<Genre | null>(null);
  function addGenre(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const name = newGenre.trim(); if (!name || genres.some((genre) => genre.name.toLowerCase() === name.toLowerCase())) return; setGenres((items) => [...items, { id: crypto.randomUUID(), name }]); setNewGenre(""); }
  function saveEdit() { if (!editing?.name.trim()) return; setGenres((items) => items.map((genre) => genre.id === editing.id ? { ...genre, name: editing.name.trim() } : genre)); setEditing(null); }
  return <div className="mx-auto max-w-5xl space-y-7"><PageHeader eyebrow="Organisation" title="Vos genres" description="Gardez une bibliothèque facile à parcourir grâce à vos propres catégories." />
    <section className="rounded-[1.75rem] border border-[#dce4d8] bg-[#fffef9] p-5 shadow-[0_12px_35px_rgba(49,76,53,0.05)] sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#e9f0e5] text-[#486b47]"><Tag className="size-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#718b6d]">Collection</p><h2 className="mt-1 font-serif text-2xl text-[#2a3c2b]">{genres.length} genre{genres.length > 1 ? "s" : ""}</h2></div></div><form className="flex w-full gap-2 sm:w-auto" onSubmit={addGenre}><input className="h-11 min-w-0 flex-1 rounded-xl border border-[#d7e1d3] bg-white px-4 text-sm text-[#314232] outline-none focus:border-[#7a9b74] focus:ring-4 focus:ring-[#315a3d]/[0.08] sm:w-64" onChange={(event) => setNewGenre(event.target.value)} placeholder="Ajouter un genre" value={newGenre} /><button className="inline-flex h-11 shrink-0 items-center gap-2 rounded-xl bg-[#314c35] px-4 text-sm font-semibold text-white transition hover:bg-[#263e2a]" type="submit"><Plus className="size-4" /> Ajouter</button></form></div></section>
    <section className="overflow-hidden rounded-[1.75rem] border border-[#dce4d8] bg-[#fffef9] shadow-[0_12px_35px_rgba(49,76,53,0.05)]"><div className="border-b border-[#e5ece1] px-5 py-4 sm:px-6"><p className="text-sm text-[#71806e]">Toutes les catégories utilisées pour organiser vos lectures.</p></div>{genres.length ? <ul className="divide-y divide-[#e7ece4]">{genres.map((genre, index) => <li className="group flex items-center gap-4 px-5 py-4 transition hover:bg-[#f8faf6] sm:px-6" key={genre.id}><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#e9f0e5] text-xs font-bold text-[#567454]">{String(index + 1).padStart(2, "0")}</span>{editing?.id === genre.id ? <><input autoFocus className="h-10 min-w-0 flex-1 rounded-xl border border-[#9ab594] bg-white px-3 text-sm font-semibold text-[#354534] outline-none" onChange={(event) => setEditing({ ...editing, name: event.target.value })} onKeyDown={(event) => { if (event.key === "Enter") saveEdit(); if (event.key === "Escape") setEditing(null); }} value={editing.name} /><div className="flex gap-1"><button aria-label="Enregistrer" className="grid size-9 place-items-center rounded-lg bg-[#e2f0dd] text-[#477342]" onClick={saveEdit} type="button"><Check className="size-4" /></button><button aria-label="Annuler" className="grid size-9 place-items-center rounded-lg text-[#768276] hover:bg-white" onClick={() => setEditing(null)} type="button"><X className="size-4" /></button></div></> : <><div className="min-w-0 flex-1"><p className="font-semibold text-[#354534]">{genre.name}</p><p className="mt-0.5 text-xs text-[#849080]">Genre de votre bibliothèque</p></div><div className="flex gap-1 opacity-100 transition sm:opacity-0 sm:group-hover:opacity-100"><button aria-label={`Modifier ${genre.name}`} className="grid size-9 place-items-center rounded-lg text-[#657464] hover:bg-white" onClick={() => setEditing(genre)} type="button"><Pencil className="size-4" /></button><button aria-label={`Supprimer ${genre.name}`} className="grid size-9 place-items-center rounded-lg text-[#b5574e] hover:bg-[#fff1ed]" onClick={() => setGenres((items) => items.filter((item) => item.id !== genre.id))} type="button"><Trash2 className="size-4" /></button></div></>}</li>)}</ul> : <div className="p-12 text-center"><Tag className="mx-auto size-8 text-[#8aa184]" /><p className="mt-3 text-sm font-semibold text-[#40513e]">Aucun genre pour le moment</p><p className="mt-1 text-xs text-[#788576]">Utilisez le champ ci-dessus pour créer le premier.</p></div>}</section>
  </div>;
}
