import Link from "next/link";
import { ArrowRight, BookOpen, Sparkles } from "lucide-react";

export function Hero() {
  return (
    <section className="relative isolate overflow-hidden">
      <div className="absolute inset-x-0 top-0 -z-10 h-[34rem] bg-[radial-gradient(circle_at_86%_20%,rgba(181,203,161,0.8),transparent_26%),radial-gradient(circle_at_8%_8%,rgba(235,202,164,0.56),transparent_25%)]" />
      <div className="mx-auto grid max-w-7xl items-center gap-14 px-6 pb-24 pt-16 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:pb-32 lg:pt-24">
        <div className="max-w-2xl"><p className="inline-flex items-center gap-2 rounded-full border border-[#bac6af] bg-[#fdfaf2]/75 px-3.5 py-2 text-xs font-bold uppercase tracking-[0.14em] text-[#466145]"><Sparkles className="size-3.5" aria-hidden="true" /> Un carnet de lecture vivant</p><h1 className="mt-6 max-w-xl font-serif text-5xl leading-[0.96] tracking-[-0.05em] sm:text-6xl lg:text-7xl">Vos lectures ne se résument pas à une liste.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#5d655a]">Gardez vos livres, reprenez exactement là où vous vous êtes arrêté et voyez votre parcours se construire, page après page.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/auth/register" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#bd704c] px-6 py-3.5 text-sm font-bold text-white shadow-[0_12px_28px_rgba(130,71,42,0.2)] transition hover:-translate-y-0.5 hover:bg-[#a85f3e]">Commencer gratuitement <ArrowRight className="size-4" aria-hidden="true" /></Link><a href="#experience" className="inline-flex items-center justify-center rounded-full border border-[#bfc5b7] bg-[#faf8f1]/70 px-6 py-3.5 text-sm font-bold text-[#344334] transition hover:border-[#7b9074] hover:bg-[#fffdf8]">Découvrir l&apos;expérience</a></div><p className="mt-7 text-sm text-[#747b70]">Un livre suffit pour commencer.</p></div>
        <div className="relative mx-auto w-full max-w-md py-10 lg:max-w-none"><div className="absolute inset-0 mx-auto size-72 rounded-full bg-[#dce5d1] blur-2xl sm:size-80" /><div className="relative ml-auto max-w-md rounded-[1.4rem] border border-[#d3d6c9] bg-[#fffdf8] p-5 shadow-[0_25px_60px_rgba(50,61,42,0.18)] sm:p-6 lg:rotate-[3deg]"><div className="mb-5 flex items-center justify-between text-xs font-medium text-[#778075]"><span>Aperçu · en cours de lecture</span><span className="rounded-full bg-[#e3eedb] px-2.5 py-1 font-bold text-[#426042]">68 %</span></div><div className="grid grid-cols-[5.25rem_1fr] gap-4 sm:grid-cols-[6.25rem_1fr]"><div className="flex aspect-[3/4] flex-col justify-between rounded-md bg-[linear-gradient(145deg,#28433c,#ab633f)] p-3 text-[#fff6e8] shadow-lg"><BookOpen className="size-4" aria-hidden="true" /><span className="font-serif text-xl leading-[0.9]">La main gauche de la nuit</span></div><div className="min-w-0 self-center"><h2 className="font-serif text-2xl leading-tight text-[#252c24]">La main gauche de la nuit</h2><p className="mt-1 text-sm text-[#6c746a]">Ursula K. Le Guin</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-[#e6e8df]"><div className="h-full w-[68%] rounded-full bg-[#bd704c]" /></div><div className="mt-2 flex justify-between text-xs text-[#6c746a]"><span>p. 214 / 315</span><span>À reprendre ce soir</span></div></div></div></div><div className="relative -bottom-4 -left-2 w-fit rounded-2xl border border-[#d3d6c9] bg-[#fffdf8] px-4 py-3 shadow-lg sm:absolute sm:left-[-1.5rem] sm:bottom-0 lg:rotate-[-3deg]"><p className="text-xs text-[#697167]">Votre rythme de lecture</p><p className="mt-1 font-serif text-2xl text-[#ad653f]">une habitude qui dure</p></div></div>
      </div>
    </section>
  );
}
