"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { BookOpen, CheckCircle2, FilePenLine, Loader2, Plus, Search } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PageHeader } from "@/components/shared/page-header";
import { useBookStore } from "@/lib/book-store";
import { fakeExternalSearchResults, fakeGenres } from "@/lib/fake-data";

type ExternalBook = (typeof fakeExternalSearchResults)[number];
const emptyManual = { title: "", author: "", description: "", totalPages: "", isbn: "", publisher: "", publishedYear: "", language: "fr", genreId: "" };

export default function SearchPage() {
  const { addBook, books } = useBookStore();
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<ExternalBook[]>([]);
  const [manualOpen, setManualOpen] = useState(false);
  const [manual, setManual] = useState(emptyManual);
  const [importing, setImporting] = useState<string | null>(null);
  const [success, setSuccess] = useState<{ id: string; title: string } | null>(null);
  const [genres, setGenres] = useState<Record<string, string>>({});
  const notify = (id: string, title: string) => { setSuccess({ id, title }); window.setTimeout(() => setSuccess(null), 4500); };
  function search(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const value = query.trim().toLowerCase(); if (!value) return; const matches = fakeExternalSearchResults.filter((book) => book.title.toLowerCase().includes(value) || book.author.toLowerCase().includes(value) || book.isbn?.includes(value)); setResults(matches.length ? matches : fakeExternalSearchResults); }
  async function importBook(book: ExternalBook) { if (books.some((item) => item.externalSourceId === book.externalSourceId)) return; setImporting(book.externalSourceId); await new Promise((resolve) => window.setTimeout(resolve, 450)); const genre = fakeGenres.find((item) => item.id === genres[book.externalSourceId]); const id = crypto.randomUUID(); addBook({ ...book, id, coverUrl: book.coverUrl ?? null, description: book.description ?? "", totalPages: book.totalPages ?? 0, isbn: book.isbn ?? "", publisher: book.publisher ?? "", publishedYear: book.publishedYear ?? 0, language: book.language ?? "fr", genre: genre ? { id: genre.id, name: genre.name } : undefined, status: "TO_READ", lastReadPage: 0, sessions: [], hasReadableContent: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); setImporting(null); notify(id, book.title); }
  function addManual(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const genre = fakeGenres.find((item) => item.id === manual.genreId); const id = crypto.randomUUID(); addBook({ id, title: manual.title, author: manual.author, description: manual.description, coverUrl: null, fileUrl: null, readOnlineUrl: null, totalPages: Number(manual.totalPages) || 0, isbn: manual.isbn, publisher: manual.publisher, publishedYear: Number(manual.publishedYear) || 0, language: manual.language, externalSourceId: "", externalSource: "manual", genre: genre ? { id: genre.id, name: genre.name } : undefined, status: "TO_READ", lastReadPage: 0, sessions: [], hasReadableContent: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); setManual(emptyManual); setManualOpen(false); notify(id, manual.title); }
  return <div className="mx-auto max-w-5xl space-y-7"><PageHeader actions={<button className="inline-flex items-center gap-2 rounded-xl border border-[#bfd3b9] bg-[#f4f8f1] px-4 py-2.5 text-sm font-bold text-[#426b42]" onClick={() => setManualOpen(true)} type="button"><Plus className="size-4" /> Ajouter manuellement</button>} description="Cherchez une référence dans le catalogue ou créez une fiche complète pour vos propres livres." eyebrow="Ajouter un livre" title="Trouver une lecture" />
    {success && <div className="flex flex-wrap justify-between gap-3 rounded-2xl border border-[#cbe0c6] bg-[#eff8ec] px-4 py-3 text-sm text-[#3f6a3f]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4" /> « {success.title} » a été ajouté.</span><Link className="font-bold underline" href={`/dashboard/books/${success.id}`}>Voir la fiche</Link></div>}
    <div className="grid max-w-4xl gap-5"><section className="rounded-[1.75rem] border border-[#d1dfca] bg-[#e7efe1] p-6 shadow-[0_14px_32px_rgba(49,76,53,0.08)] sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#567454]">Catalogue</p><h2 className="mt-2 font-serif text-3xl text-[#2d422f]">Quel livre cherchez-vous ?</h2><p className="mt-2 text-sm leading-6 text-[#627461]">Recherchez par titre, auteur ou ISBN, puis ajoutez la référence à votre bibliothèque.</p><form className="mt-6 flex flex-col gap-3 sm:flex-row" onSubmit={search}><div className="relative flex-1"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-[#6f866d]" /><input className="h-12 w-full rounded-xl border border-[#c6d8bf] bg-white px-12 text-sm text-[#314232] outline-none" onChange={(event) => setQuery(event.target.value)} placeholder="Titre, auteur ou ISBN" value={query} /></div><button className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#426b42] px-6 text-sm font-bold text-white" type="submit"><Search className="size-4" /> Rechercher</button></form></section><section className="rounded-[1.75rem] border border-[#dce4d8] bg-[#fffef9] p-6 shadow-[0_14px_32px_rgba(49,76,53,0.05)] sm:p-8"><FilePenLine className="size-6 text-[#5c7c59]" /><p className="mt-5 font-serif text-2xl text-[#2e3d2e]">Un titre introuvable ?</p><p className="mt-2 text-sm leading-6 text-[#71806e]">Créez une fiche détaillée avec son résumé, son ISBN, son éditeur et son genre.</p><button className="mt-5 inline-flex items-center gap-2 rounded-xl border border-[#bfd3b9] bg-[#f4f8f1] px-4 py-2.5 text-sm font-bold text-[#426b42]" onClick={() => setManualOpen(true)} type="button"><Plus className="size-4" /> Ajouter manuellement</button></section></div>
    {results.length ? <section><h2 className="mb-4 font-serif text-2xl text-[#2e3d2e]">Résultats trouvés</h2><div className="grid gap-4 md:grid-cols-2">{results.map((book) => <Result book={book} exists={books.some((item) => item.externalSourceId === book.externalSourceId)} genreId={genres[book.externalSourceId] ?? ""} importing={importing === book.externalSourceId} key={book.externalSourceId} onGenre={(id) => setGenres({ ...genres, [book.externalSourceId]: id })} onImport={() => void importBook(book)} />)}</div></section> : <section className="rounded-[1.75rem] border border-dashed border-[#cfdbca] bg-[#f8fbf6] p-12 text-center"><BookOpen className="mx-auto size-9 text-[#819a7c]" /><p className="mt-4 font-serif text-2xl text-[#405040]">Une idée de lecture ?</p><p className="mt-2 text-sm text-[#71806e]">Recherchez un titre, un auteur ou un ISBN pour commencer.</p></section>}
    <Dialog open={manualOpen} onOpenChange={setManualOpen}><DialogContent className="max-h-[calc(100vh-1rem)] max-w-[calc(100%-1rem)] overflow-y-auto rounded-[1.75rem] border-[#dce4d7] bg-[#fffef9] p-6 sm:!max-w-3xl"><DialogHeader><DialogTitle className="font-serif text-2xl text-[#2b382b]">Ajouter un livre manuellement</DialogTitle><DialogDescription>Renseignez ce que vous connaissez : vous pourrez modifier cette fiche plus tard.</DialogDescription></DialogHeader><form className="space-y-4 pt-4" onSubmit={addManual}><div className="grid gap-4 sm:grid-cols-2"><Input label="Titre *" required value={manual.title} onValue={(value) => setManual({ ...manual, title: value })} /><Input label="Auteur *" required value={manual.author} onValue={(value) => setManual({ ...manual, author: value })} /><Input label="ISBN" value={manual.isbn} onValue={(value) => setManual({ ...manual, isbn: value })} /><Input label="Nombre de pages" type="number" value={manual.totalPages} onValue={(value) => setManual({ ...manual, totalPages: value })} /><Input label="Éditeur" value={manual.publisher} onValue={(value) => setManual({ ...manual, publisher: value })} /><Input label="Année de publication" type="number" value={manual.publishedYear} onValue={(value) => setManual({ ...manual, publishedYear: value })} /><Select label="Langue" value={manual.language} onValue={(value) => setManual({ ...manual, language: value })}><option value="fr">Français</option><option value="en">Anglais</option><option value="es">Espagnol</option></Select><Select label="Genre" value={manual.genreId} onValue={(value) => setManual({ ...manual, genreId: value })}><option value="">Sans genre</option>{fakeGenres.map((genre) => <option key={genre.id} value={genre.id}>{genre.name}</option>)}</Select></div><label className="block text-sm font-semibold text-[#405040]">Résumé<textarea className="mt-2 min-h-28 w-full rounded-xl border border-[#d7e1d3] bg-white px-4 py-3 text-sm font-normal outline-none" onChange={(event) => setManual({ ...manual, description: event.target.value })} value={manual.description} /></label><button className="inline-flex w-full justify-center gap-2 rounded-xl bg-[#426b42] px-4 py-3 text-sm font-semibold text-white" type="submit"><Plus className="size-4" /> Ajouter à la bibliothèque</button></form></DialogContent></Dialog>
  </div>;
}
function Result({ book, exists, genreId, importing, onGenre, onImport }: { book: ExternalBook; exists: boolean; genreId: string; importing: boolean; onGenre: (value: string) => void; onImport: () => void }) { return <article className="flex gap-4 rounded-2xl border border-[#dce4d8] bg-[#fffef9] p-4"><div className="relative h-32 w-[5.5rem] shrink-0 overflow-hidden rounded-xl bg-[#edf3e9]">{book.coverUrl ? <Image alt={`Couverture de ${book.title}`} className="object-cover" fill sizes="88px" src={book.coverUrl} /> : <BookOpen className="m-auto mt-12 size-5 text-[#8aa184]" />}</div><div className="min-w-0 flex-1"><h3 className="truncate font-serif text-xl text-[#304030]">{book.title}</h3><p className="mt-1 truncate text-sm text-[#728070]">{book.author}</p><select className="mt-4 h-9 w-full rounded-lg border border-[#dce5d8] bg-white px-2 text-xs" onChange={(event) => onGenre(event.target.value)} value={genreId}><option value="">Genre facultatif</option>{fakeGenres.map((genre) => <option key={genre.id} value={genre.id}>{genre.name}</option>)}</select><button className={`mt-3 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${exists ? "bg-[#edf1eb] text-[#71806e]" : "bg-[#426b42] text-white"}`} disabled={exists || importing} onClick={onImport} type="button">{importing ? <Loader2 className="size-3.5 animate-spin" /> : exists ? <CheckCircle2 className="size-3.5" /> : <Plus className="size-3.5" />}{exists ? "Déjà ajouté" : "Ajouter"}</button></div></article>; }
function Input({ label, onValue, ...props }: Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange"> & { label: string; onValue: (value: string) => void }) { return <label className="block text-sm font-semibold text-[#405040]">{label}<input {...props} className="mt-2 h-11 w-full rounded-xl border border-[#d7e1d3] bg-white px-4 text-sm font-normal outline-none" onChange={(event) => onValue(event.target.value)} /></label>; }
function Select({ children, label, onValue, value }: { children: React.ReactNode; label: string; onValue: (value: string) => void; value: string }) { return <label className="block text-sm font-semibold text-[#405040]">{label}<select className="mt-2 h-11 w-full rounded-xl border border-[#d7e1d3] bg-white px-4 text-sm font-normal outline-none" onChange={(event) => onValue(event.target.value)} value={value}>{children}</select></label>; }
